# Generated by Django 2.2.9 on 2020-01-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200103_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='Adres'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(default='İlçe', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='İsim', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='5554443322', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(default='İl', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(default='Soyisim', max_length=50),
        ),
    ]
